name: Setup
description: Setup the environment

runs:
  using: composite
  steps:
    - name: (linux) Print Linux system info
      if: matrix.os == 'ubuntu-22.04'
      shell: bash
      run: |
        cat /etc/os-release

    - name: (macos) Print macOS system info
      if: matrix.os == 'macos-14'
      shell: bash
      run: |
        sw_vers

    - name: (windows) Print Windows system info
      if: matrix.os == 'windows-2022'
      shell: pwsh
      run: |
        Get-ComputerInfo | Format-List *
