name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  WGPU_DX12_COMPILER: dxc
  RUSTFLAGS: --cfg=web_sys_unstable_apis
  RUST_BACKTRACE: 1
  DXC_RELEASE: "v1.7.2308"
  DXC_FILENAME: "dxc_2023_08_14.zip"
  WASM_BINDGEN_TEST_TIMEOUT: 300 # 5 minutes

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            platform: win64

          - name: Linux x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            platform: linux64

          - name: MacOS aarch64
            os: macos-14
            target: aarch64-apple-darwin
            platform: mac-arm64

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: run tests
        shell: bash
        run: |
          echo "Running tests"
          date
